# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"!\n\x0c\x46raudRequest\x12\x11\n\ttotal_qty\x18\x01 \x01(\x05\"2\n\rFraudResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2h\n\x15\x46raudDetectionService\x12O\n\x0e\x46raudDetection\x12\x1d.fraud_detection.FraudRequest\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAUDREQUEST']._serialized_start=42
  _globals['_FRAUDREQUEST']._serialized_end=75
  _globals['_FRAUDRESPONSE']._serialized_start=77
  _globals['_FRAUDRESPONSE']._serialized_end=127
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=129
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
