# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"0\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"C\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x10HeartbeatRequest\x12\x18\n\x10\x66rom_database_id\x18\x01 \x01(\x05\"\"\n\x11HeartbeatResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"+\n\x0f\x45lectionRequest\x12\x18\n\x10\x66rom_database_id\x18\x01 \x01(\x05\"(\n\x10\x45lectionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"+\n\x12\x43oordinatorMessage\x12\x15\n\rnew_leader_id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xd5\x02\n\x0f\x44\x61tabaseService\x12\x35\n\x04Read\x12\x15.database.ReadRequest\x1a\x16.database.ReadResponse\x12\x38\n\x05Write\x12\x16.database.WriteRequest\x1a\x17.database.WriteResponse\x12H\n\rSendHeartbeat\x12\x1a.database.HeartbeatRequest\x1a\x1b.database.HeartbeatResponse\x12\x46\n\rStartElection\x12\x19.database.ElectionRequest\x1a\x1a.database.ElectionResponse\x12?\n\x0e\x41nnounceLeader\x12\x1c.database.CoordinatorMessage\x1a\x0f.database.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READREQUEST']._serialized_start=28
  _globals['_READREQUEST']._serialized_end=56
  _globals['_READRESPONSE']._serialized_start=58
  _globals['_READRESPONSE']._serialized_end=106
  _globals['_WRITEREQUEST']._serialized_start=108
  _globals['_WRITEREQUEST']._serialized_end=175
  _globals['_WRITERESPONSE']._serialized_start=177
  _globals['_WRITERESPONSE']._serialized_end=209
  _globals['_HEARTBEATREQUEST']._serialized_start=211
  _globals['_HEARTBEATREQUEST']._serialized_end=255
  _globals['_HEARTBEATRESPONSE']._serialized_start=257
  _globals['_HEARTBEATRESPONSE']._serialized_end=291
  _globals['_ELECTIONREQUEST']._serialized_start=293
  _globals['_ELECTIONREQUEST']._serialized_end=336
  _globals['_ELECTIONRESPONSE']._serialized_start=338
  _globals['_ELECTIONRESPONSE']._serialized_end=378
  _globals['_COORDINATORMESSAGE']._serialized_start=380
  _globals['_COORDINATORMESSAGE']._serialized_end=423
  _globals['_EMPTY']._serialized_start=425
  _globals['_EMPTY']._serialized_end=432
  _globals['_DATABASESERVICE']._serialized_start=435
  _globals['_DATABASESERVICE']._serialized_end=776
# @@protoc_insertion_point(module_scope)
